spring:
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 525296980706-ceu07qdchqi93jd3don8h9sgmn99hj7l.apps.googleusercontent.com
            clientSecret: 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
            scope: openid,profile,email,https://www.googleapis.com/auth/youtube

logging:
  level:
    com.example.spring.oauth: DEBUG
    org.springframework.security: TRACE
    org.springframework.security.oauth2: TRACE
    org.springframework.web: TRACE
    org.springframework.web.reactive: TRACE
